/* Project Euler: Problem 2: Even Fibonacci Numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence that do not exceed the nth term, find the sum of the even-valued terms. */


function fiboEvenSum(n) {
  const cache = {};
  function fibonacci(n){
     if(n <= 1) return 1;
     if(n in cache) return cache[n];
     return cache[n] = fibonacci(n-1) + fibonacci(n-2);
     
  }
  fibonacci(n);

  return Object.values(cache).filter( f => f % 2 === 0).reduce( (evenSum,cur) => evenSum + cur, 0 );
}
